### ISSUE TITLE
[imaging_browser] click on QC comments on image returns blank page

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4722]
TestPlan Item B14. `Verify Visit-level QC controls and comments can be deleted/unchecked/emptied and saved`

Problem:
Click on QC comments on image returns blank page
e.g., ROM184_400184_V3: loris_400184_V3_t1_001.mnc
`This page isn’t working test.loris.ca is currently unable to handle this request.
HTTP ERROR 500`

**Comment by driusan** [comment]
Are you sure this isn't a problem with test.loris.ca? Can you try on another sandbox?

**Comment by coreyAbout** [comment]
> Are you sure this isn't a problem with test.loris.ca? Can you try on another sandbox?

Haven't tried yet. Currently developing the instance for Douglas, switching to raisinbread involves switching the code base, the database tables, and all the kinds of imaging files. Need to switch back and forth, haven't figured out best way to do it now.

Can you try that on your sandbox?

**Comment by johnsaigle** [comment]
Addressed by #4734

**Comment by zaliqarosli** [comment]
@johnsaigle just to double-check, this issue can be closed right?

**Comment by cmadjar** [comment]
Now the QC comments show the page but the check boxes are missing. This is still an issue to be fixed. I'll add the "Critical to release" Tag as not being able to do QC seems like an important bug and remove the PR sent tag since this still needs fixing

**Comment by cmadjar** [comment]
I removed the tag critical to release since it was a bug in the raisin bread dataset and not the code. I sent a PR to modify the RB dataset on the LORIS code to fix the issue.

**Comment by zaliqarosli** [comment]
thanks @cmadjar !

**Comment by driusan** [comment]
fixed by above PR
