### ISSUE TITLE
[BVL Feedback] No BVL Feedback link at the instrument level

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#6259]
There is no way to access the Behavioral Feedback when accessing an instrument. It is only available at the Candidate and Visit level. 

![Screen Shot 2020-04-04 at 8 07 23 PM](https://user-images.githubusercontent.com/54332302/78463871-2678e400-76b0-11ea-9bc5-80f460434d24.png)

**Comment by johnsaigle** [comment]
I think this is resolved by the linked PR

**Comment by SantiagoTG** [comment]
Reopening as issue is still present. BHV feedback link still missing at the instrument level.

**Comment by driusan** [comment]
@SantiagoTG how did you test?

**Comment by SantiagoTG** [comment]
Hi Dave, I tested the same way I did initially, by entering https://test-loris-dev.loris.ca/ and checking the BVL feedback links for a given candidate.

**Comment by johnsaigle** [comment]
Is the Test VM up to date?

**Comment by lingma** [comment]
I just checked, the new 23.0 should be OK. But not on the test VM
