### ISSUE TITLE
[Publication] Can't submit Project proposal

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#7880]
**Describe the bug**
Afete several attempts, the 'Propose project' on the 'Propose a project' tab of the Publication module no longer appears to work. Previously I had attempted submitting several proposals with a 'Attempt to use pselectRow on a query that returns multiple rows' error being displayed as specified on https://github.com/aces/Loris/issues/7877. 

However, now I can no longer submit any proposal and no error message appears. I tried reloading the module and the same. Tried various combinations for the field entries and emails used, but none worked.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'Publications module and try to propose a new project.'

**Comment by ridz1208** [comment]
@SantiagoTG the linked issue was closed because you were not able to reproduce. is this one still valid ?

**Comment by SantiagoTG** [comment]
I am now able to propose a new project on demo.loris.ca (assuming it is on 24.0). However, if I try attaching a file when proposing a new project, an error message will appear and the project will not be created. 

**Error message:**

<img width="554" alt="Screenshot 2023-01-17 at 11 16 29 AM" src="https://user-images.githubusercontent.com/54332302/212958364-9ef765f2-3a8f-46ac-a56a-ceb736a11c43.png">



Creating the project without the attached file, and then going into the newly created publication and adding a new attachment will display a success message, apparently successfully adding the file to the publication. 

<img width="975" alt="Screenshot 2023-01-17 at 11 52 30 AM" src="https://user-images.githubusercontent.com/54332302/212962041-764ba33b-41f0-41bc-88de-26332fe08cf3.png">


However, no file is actually attached and the entered data for the attachment is not available when opening the publication.

**Comment by ridz1208** [comment]
@SantiagoTG the first part is my bad. I just fixed it please try again. the second part might also be fixed however the fact that it doesnt report an error is worrying. might still be an issue on it's own

**Comment by SantiagoTG** [comment]
I am now able to propose a new project including an attachment, which is successfully reported and include the attachment when opening the publication entry. 

However, if on the other hand I create a new publication, and after creating the publication I add a new attachment, it reports the edit was successful, but no attachment will be added to the publication.

**Comment by skarya22** [comment]
The last comment is still an issue -- the original issue is not an issue though
